app_stack_size = 32768
board = "xiao-s3-kit"

[global_conf.wifi]
ssid = "ssid-here"
pw = "pw-here"

[[nodes]]
slot = "companion-0"
layers = ["CompanionBuilder<0, 5000>", "PingBot"]

[[nodes]]
slot = "companion-1"
layers = ["CompanionBuilder<1, 3000>"]